---
title: "bio_csus_uw"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE}
install.packages("")
```

```{r, include = FALSE}
library(plyr)
library(readtext)
library(stringr)
library(quanteda)
library(ggfortify)
library(FactoMineR)
library(factoextra)
library(openxlsx)
library(alluvial)
library(ggalluvial)
library(data.table)
library(ggrepel)
library(ggfittext)
```

```{r}
### IMPORT DATA/CREATE SUBSETS  ###
###################################

data_wk2 <- readtext("/Users/ryanharris/Downloads/Bio2_Sp21_Week2_Survey_JM_RH.xlsx")
data_wk14 <- readtext("/Users/ryanharris/Downloads/Bio2_Sp21_Week14_Survey_JM_RH.xlsx")
data_alv <- readtext("/Users/ryanharris/Desktop/merged.xlsx")

subset_wk2 <- data_wk2[ -c(1:3) ]
subset_wk14 <- data_wk14[ -c(1) ]

colnames(subset_wk2) <- c("Participant.ID", "q1.2", "q2.2", "q3.2", "lecture")
colnames(subset_wk14) <- c("Participant.ID", "q1.14", "q2.14", "q3.14", "lecture")

merged_data <- merge(subset_wk2, subset_wk14, by.x = "Participant.ID", by.y = "Participant.ID")
merged_data <- merged_data[ -c(9) ]

data_alv <- data_alv[-c(1)]
colnames(data_alv) <- c("Participant.ID", "survey", "q1", "q2", "q3", "lecture")
```

```{r}
### OMIT THOSE THAT AGREE BOTH TIMES SUBSET ###
###############################################

omit_2agree <- merged_data[ !(merged_data$q2.2 == "agree" & merged_data$q2.14 == "agree"), ]
#write.xlsx(omit_2agree, file = "no_both_agree")
### INCREASING SUBSET ###
#########################

increasing <- omit_2agree[ !(omit_2agree$q2.2 == "somewhat agree" & omit_2agree$q2.14 == "somewhat agree"), ]
increasing <- increasing[ !(increasing$q2.2 == "I don't know" & increasing$q2.14 == "I don't know"), ]
increasing <- increasing[ !(increasing$q2.2 == "somewhat disagree" & increasing$q2.14 == "somewhat disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "disagree" & increasing$q2.14 == "disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "agree" & increasing$q2.14 == "somewhat agree"), ]
increasing <- increasing[ !(increasing$q2.2 == "agree" & increasing$q2.14 == "I don't know"), ]
increasing <- increasing[ !(increasing$q2.2 == "agree" & increasing$q2.14 == "somewhat disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "agree" & increasing$q2.14 == "disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "somewhat agree" & increasing$q2.14 == "I don't know"), ]
increasing <- increasing[ !(increasing$q2.2 == "somewhat agree" & increasing$q2.14 == "somewhat disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "somewhat agree" & increasing$q2.14 == "disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "I don't know" & increasing$q2.14 == "somewhat disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "I don't know" & increasing$q2.14 == "disagree"), ]
increasing <- increasing[ !(increasing$q2.2 == "somewhat disagree" & increasing$q2.14 == "disagree"), ]
#write.xlsx(increasing, file = "increasing")
### DECREASING SUBSET ###
#########################

decreasing <- omit_2agree[ !(omit_2agree$q2.2 == "somewhat agree" & omit_2agree$q2.14 == "somewhat agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "I don't know" & decreasing$q2.14 == "I don't know"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "somewhat disagree" & decreasing$q2.14 == "somewhat disagree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "disagree" & decreasing$q2.14 == "disagree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "somewhat agree" & decreasing$q2.14 == "agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "I don't know" & decreasing$q2.14 == "somewhat agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "I don't know" & decreasing$q2.14 == "agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "somewhat disagree" & decreasing$q2.14 == "I don't know"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "somewhat disagree" & decreasing$q2.14 == "somewhat agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "somewhat disagree" & decreasing$q2.14 == "agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "disagree" & decreasing$q2.14 == "somewhat disagree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "disagree" & decreasing$q2.14 == "I don't know"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "disagree" & decreasing$q2.14 == "somewhat agree"), ]
decreasing <- decreasing[ !(decreasing$q2.2 == "disagree" & decreasing$q2.14 == "agree"), ]
decreasing
#write.xlsx(decreasing, file = "decreasing")
```

```{r}
likert <- omit_2agree[ -c(2, 4, 5, 6, 8) ]
likert_num2 <- revalue(likert$q2.2, c("agree" = 5, "somewhat agree" = 4, "I don't know" = 3, "somewhat disagree" = 2, "disagree" = 1))
likert_num14 <- revalue(likert$q2.14, c("agree" = "5", "somewhat agree" = "4", "I don't know" = "3", "somewhat disagree" = "2", "disagree" = "1"))
likert_num <- cbind(likert, likert_num2, likert_num14)
likert_num <- likert_num[ -c(1,2,3) ]
likert_num <- data.frame(lapply(likert_num,as.numeric))
summary(likert_num)
likert_num
```

```{r}
### ALLUVIAL DIAGRAMS ###
#########################

drops <- c("Participant.ID", "q1.2", "q3.2", "q1.14", "q3.14")
alluvial1 <- omit_2agree[ , !(names(omit_2agree) %in% drops)]
freq_data <- setDT(alluvial1)[,rep(.N,.N),.(q2.2, lecture.x, q2.14)]
plot1 <- alluvial(freq_data[,1:3], freq=freq_data$V1)
```
```{r, warning = FALSE}
ggplot(data_alv, aes(x = survey, stratum = q2, alluvium = Participant.ID)) +
  geom_alluvium(aes(fill = lecture)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), min.y = 4) 
  # geom_text_repel(aes(label = ifelse(survey == 1, q2, NA)), stat = "stratum", size = 3, direction = "y",   nudge_x = -.5) +
  # geom_text_repel(aes(label = ifelse(survey == 2, q2, NA)), stat = "stratum", size = 3, direction = "y",   nudge_x = -.5)

ggplot(merged_data, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.14)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), min.y = 4)

ggplot(merged_data, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.2)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(merged_data, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = lecture.x)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))
```


```{r, warning = FALSE}
### MERGED DATA WITHOUT BOTH AGREE  ###
#######################################

ggplot(alluvial1, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.14)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(alluvial1, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.2)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(alluvial1, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = lecture.x)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))
```

```{r, warning = FALSE}
### INCREASING SUBSET ###
#########################

ggplot(increasing, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.14)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(increasing, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.2)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(increasing, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = lecture.x)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))
```

```{r, warning = FALSE}
### DECREASING SUBSET ###
#########################

ggplot(decreasing, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.14)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(decreasing, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = q2.2)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))

ggplot(decreasing, aes(axis1 = q2.2, axis2 = lecture.x, axis3 = q2.14)) +
  geom_alluvium(aes(fill = lecture.x)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))
```

```{r}
### CREATE DTM  ###
###################

# data5 <- data_wk2[, 5]
# data5_corp <- corpus(data5)
# dtm5 <- dfm(data5_corp, tolower = TRUE, remove_punct = TRUE, stem = TRUE, remove = stopwords("english"))
# dtm5freq <- docfreq(dtm5)
# dtm5 <- dtm5[, dtm5freq >= 2]
# #dtm5 <- dfm_weight(dtm5, "tfidf")
# dtm5
# 
# data7 <- data_wk2[, 7]
# data7_corp <- corpus(data7)
# dtm7 <- dfm(data7_corp, tolower = TRUE, remove_punct = TRUE, stem = TRUE, remove = stopwords("english"))
# dtm7freq <- docfreq(dtm7)
# dtm7 <- dtm7[, dtm7freq >= 2]
# #dtm7 <- dfm_weight(dtm7, "tfidf")
# dtm7
```

```{r}
### DICTIONARY AND COUNTING ###
###############################

# download.file("http://bit.ly/37cV95h", tf <- tempfile())
# myDict <- dictionary(file = tf, format = "LIWC")
# dict_dtm5 <- dfm_lookup(dtm5, myDict, nomatch = "_unmatched")
# dict_dtm5
# 
# dict_dtm7 <- dfm_lookup(dtm7, myDict, nomatch = "_unmatched")
# dict_dtm7
```

```{r}
### PCA ###
###########

# dtm5.pca <- prcomp(dtm5, scale = TRUE)
# dtm7.pca <- prcomp(dtm7, scale = TRUE)
# fviz_eig(dtm5.pca)
# fviz_eig(dtm7.pca)
# 
# eig.val <- get_eigenvalue(dtm5.pca)
# eig.val
```

```{r}

```
